version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: zeus-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-zeus}
      POSTGRES_USER: ${POSTGRES_USER:-zeus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zeus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-zeus} -d ${POSTGRES_DB:-zeus}"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: zeus-redis-prod
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    networks:
      - zeus-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  zeus:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: zeus-app-prod
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - APP_PORT=${APP_PORT:-8080}
      - APP_ENV=${APP_ENV:-production}
      - APP_RATE_LIMIT_PER_MIN=${APP_RATE_LIMIT_PER_MIN:-1000}
      - APP_OTP_TTL_SECONDS=${APP_OTP_TTL_SECONDS:-300}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - APP_JWT_EXPIRES_MINUTES=${APP_JWT_EXPIRES_MINUTES:-60}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-zeus}
      - POSTGRES_USER=${POSTGRES_USER:-zeus}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB:-0}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - zeus-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  pgdata:
  redisdata:

networks:
  zeus-network:
    driver: bridge
